platform :ios, '9.2'
use_frameworks!

target 'bobafetch' do
    pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
    pod 'Alamofire', '~> 3.1.5'
    pod 'AWSS3'
    pod 'ENSwiftSideMenu', '~> 0.1'
    pod 'Stripe', :git => 'https://github.com/stripe/stripe-ios'
end

